/**
 * @File Name          : testFile_SFDXAutoheader.apex
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 2019-02-27, 12:17:35 a.m.
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    2019-02-27, 12:17:30 a.m.   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public class tester {

    public static Map<Id, List<Account>> testMethod( 
      Map<String, Map<Integer, List<Account>>> mapListAcc,
      List<Account> listAccount, 
      Integer i,  
      Map<Id, List<Account>> mapListAcc,
      List<List<Table>> lstListTab,
      Integer j,
      Boolean isTrue,
      Map<  Id, Map<String, List<Time>>>     TimeLostMap
    ) {
      
    }

    void testMethod2(Integer i, List<Account> lstAcc) {}

    public static Map<Id, Map<String, Account>> testMethod( 
      Map<String, Map<Integer, List<Account>>> mapListAcc,
      List<Account> listAccount, 
      Integer i,  
      Map<Id, List<Account>> mapListAcc,
      List<List<Table>> lstListTab,
      Integer j,
      Boolean isTrue,
      Map<  Id, Map<String, List<Time>>>     TimeLostMap
    ) {
      
    }
       
    global override List<Account> getAccount() {
      
    }


}