public class tester {

    public static Map<Id, List<Account>> testMethod( 
      Map<String, Map<Integer, List<Account>>> mapListAcc,
      List<Account> listAccount, 
      Integer i,  
      Map<Id, List<Account>> mapListAcc,
      List<List<Table>> lstListTab, 
      Integer j,
      Boolean isTrue,
      Map<  Id, Map<String, List<Time>>>     TimeLostMap
    ) {    
                
    }   

    void testMethod2(Integer i, List<List <Account>> lstAcc) {}

    public static Map<Id, Map<String, Account>> testMethod( 
      Map<String, Map<Integer, List<Account>>> mapListAcc,
      List<Account> listAccount, 
      Integer i,  
      Map<Id, List<Account>> mapListAcc,
      List<List<Table>> lstListTab,
      Integer j, 
      Boolean isTrue, 
      Map<  Id, Map<String, List<Time>>>     TimeLostMap
    ) {
      
    }
       
    global override List<Account> getAccount() {
       
    }


}